version: '3'
services:
  node1:
    build: .
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - NET_RAW
      - NET_ADMIN

  node2:
    build: .
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - NET_RAW
      - NET_ADMIN

  node3:
    build: .
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - NET_RAW
      - NET_ADMIN

networks:
  my_network:
    driver: bridge
